### PR TITLE
NonBlockingJsonParser implements ByteBufferFeeder

### PR DESCRIPTION
**Pull request by kptfh**
Should fix [https://github.com/FasterXML/jackson-core/issues/478](https://github.com/FasterXML/jackson-core/issues/478)

### CODE REVIEW

**Comment by kptfh** [comment]
@cowtowncoder Should it add much performance penalties?

**Comment by cowtowncoder** [comment]
Before considering adding one specific layer of wrapping, I would want actual performance measurements to show it does not hurt performance. Based on past experience I would expect going via `ByteBuffer` to add measurable amount of overhead (work was with `aalto-xml`).

**Comment by pjfanning** [comment]
This is probably unnecessary now due to https://github.com/FasterXML/jackson-core/pull/795 - that latter PR adds dedicated byte buffer support as opposed to changing the byte array support to support buffers and arrays.

**Comment by cowtowncoder** [comment]
Agreed @pjfanning, closing.

**Pull request closed without merging**
