### PR TITLE
Add `JsonFactory.Feature` to disable charset detection

### PR DESCRIPTION
**Pull request by yawkat**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Ok this looks nice and reasonable. But let me think about this for just a bit before merging. :)

Thank you again!

**Comment by cowtowncoder** [comment]
Oh, one idea/suggestion: although `JsonFactory.Feature` is easier to add, making is `JsonReadFeature` would allow per-call changes (at least when used via `ObjectReader`).
In case someone wanted to change this more dynamically.

I don't have strong opinion but this just occurred to me and thought I'd share.

**Comment by yawkat** [comment]
@cowtowncoder i used a JsonFactory.Feature because it was easier in this case. it looks like JsonReadFeature also requires a JsonParser.Feature at the moment, which did not seem appropriate here, the other JsonParser.Features seem more like they operate to all formats (not just bytes). Do you think it should be a JsonParser.Feature as well, or should I figure out something to add a JsonReadFeature without a JsonParser.Feature?

**Comment by cowtowncoder** [comment]
> @cowtowncoder i used a JsonFactory.Feature because it was easier in this case. it looks like JsonReadFeature also requires a JsonParser.Feature at the moment, which did not seem appropriate here, the other JsonParser.Features seem more like they operate to all formats (not just bytes). Do you think it should be a JsonParser.Feature as well, or should I figure out something to add a JsonReadFeature without a JsonParser.Feature?

Good point. Unfortunately coupling for 2.x remains (untangling is not super easy), so let's just leave things the way they are as `JsonFactory.Feature`.
We can reconsider this for 3.0 if there are reasons to change it.

**Review by cowtowncoder — APPROVED** [review]

**Comment by yawkat** [comment]
ok thanks!

**Pull request merged**
