### PR TITLE
Append result to supplied StringBuilder instead of returning it.

### PR DESCRIPTION
**Pull request by mikaelstaldal**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Looks good to me, but just one question: would it make sense to take `java.lang.Appendable` instead of `StringBuilder`? That would make this even more widely usable.

**Comment by mikaelstaldal** [comment]
I considered `java.lang.Appendable`, but it lacks the `append(char[] str, int offset, int len)` method. And it forces you to handle `IOException` which is annoying.

**Comment by mikaelstaldal** [comment]
It occurred to me that now when the new method have two parameters, it can have the same name as the old method `quoteAsString`.

**Comment by cowtowncoder** [comment]
@mikaelstaldal Ok.

**Pull request merged**
