### PR TITLE
Refactor #827 a bit

### PR DESCRIPTION
**Pull request by cowtowncoder**

### CODE REVIEW

**Comment by abdullahali99** [comment]
Hi

What is the plan to release 2.15? Any specific date?

**Comment by cowtowncoder** [comment]
@abdullahali99 The usual OSS way: when it is ready. No specific plans as of now. As you can see here:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15

the set of changes so far is quite small.

**Comment by abdullahali99** [comment]
Thanks for your replay
Is it going to have fix for the sonatype vulnerability? In my company we are stuck because of this issue

**Comment by cowtowncoder** [comment]
@abdullahali99 No. The original change, #827, would resolve resource consumption concerns.

**Comment by cowtowncoder** [comment]
@DarthHater No. Requires API changes, behavioral change etc; cannot go in a patch.

**Pull request merged**
