### PR TITLE
#2013: add support for reading from / writing to a Path

### PR DESCRIPTION
**Pull request by sdoeringNew**
Is there no need to write Unit tests? The changed ``TextualTSFactory`` has barely coverage.

### CODE REVIEW

**Comment by sdoeringNew** [comment]
After getting the permission to add some Unit tests those tests have been added.

Have you noticed that the Unit tests in this project are still JUnit 3?

**Comment by cowtowncoder** [comment]
Junit dependency itself is to 4.x isn't it? As to test style, if it ain't broke... if there are specific improvement ideas those are always good to suggest of course; and if there are questions of why certain things are certain way, can file issues.

**Comment by cowtowncoder** [comment]
Merged; big thank you for increased test coverage! Although methods are quite trivial, there have been cases where even simplest implementations have had some odd edge cases (occasionally silly things like infinite recursion due to refactoring etc).

**Comment by cowtowncoder** [comment]
Quick note: missed the fact that `BinaryTSFactory` also needs new methods... shouldn't be too difficult to add, but just noticed when trying to compile binary format backends.
Just noting for posterity.

**Comment by sdoeringNew** [comment]
> Quick note: missed the fact that `BinaryTSFactory` also needs new methods... shouldn't be too difficult to add, but just noticed when trying to compile binary format backends.
> Just noting for posterity.

Good to know. I'll look at it the next two weeks.

**Comment by cowtowncoder** [comment]
@sdoeringNew no need; I added the methods :)
(plus added "tests" that subclass binary/textual base types, so if adding abstract methods should notice missing implementations [unless IDE tries to be too helpful etc])

**Pull request merged**
