### PR TITLE
Add JsonParser feature to ignore trailing commas (#118)

### PR DESCRIPTION
**Pull request by bdhess**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Thank you for the contribution! I will have to take a look here, partly since changes occur within critical-path from performance perspective. This will probably also need to go after 2.7.0, but that will give bit more time to ensure everything works properly.

**Comment by bdhess** [comment]
I did clean up the language in the Javadoc and force-pushed over it.  Hope that didn't disturb you!  Looking forward to following up.

**Comment by bdhess** [comment]
@cowtowncoder - can I trouble you to bump this up for review?  Just rebased against the latest in master.  I've run the perf tests and the difference is negligible.

**Comment by cowtowncoder** [comment]
Forgot to add a note, but I think #117 covers same issue to some degree. It will induce `null`s, which may be different, but at least allows usage.

**Pull request closed without merging**
