### PR TITLE
Remove superfluous toString convenience methods

### PR DESCRIPTION
**Pull request by BELUGABEHR**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Looks like actual use in 2.x was from `IntNode`, `LongNode`, although arguably with little benefit. So makes sense to remove. Thanks!

**Comment by cowtowncoder** [comment]
Annnnd this broke `jackson-databind` master. :-( :-( :-(

I should know better than blindly merge method removal.

**Comment by BELUGABEHR** [comment]
Ugh. Sorry!

Well it passed all the unit tests and this is the 3.0 release so we should
be able to at least deprecate.

**Comment by cowtowncoder** [comment]
@BELUGABEHR yeah no huge problem, I went ahead and replaced uses; no point in optimizing those cases.

Would also be neat to figure out how to make build chains for deps work on Travis or something.

**Pull request merged**
