### PR TITLE
Fix #418 ArrayIndexOutOfBoundsException

### LINKED ISSUE #382: ArrayIndexOutOfBoundsException from UTF32Reader.read on invalid input
We are doing some fuzz testing on internal projects and found some input that causes an unexpected exception from JsonParser. While it is throwing an exception and stopping on this, it should probably be some kind of IOException rather than an ArrayIndexOutOfBoundsException.

In our case we are catching the three exception types listed in ObjectMapper.readTree  (JsonParseException | JsonProcessingException | IOException) and this managed to escape.

Simple test case follows
```java
public void testInvalidInput() throws IOException {

        byte[] data = {
                0x00,
                0x00,
                0x00,
                0x20,
                (byte) 0xFE,
                (byte) 0xFF,
                0x00,
                0x01,
                (byte) 0xFB
        };

        JsonFactory FACTORY = new JsonFactory();
        JsonParser parser = FACTORY.createParser(data);

        parser.nextToken();


    }
```

stack trace:
```
java.lang.ArrayIndexOutOfBoundsException: 9

	at com.fasterxml.jackson.core.io.UTF32Reader.read(UTF32Reader.java:138)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:243)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2331)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:646)
	at com.fasterxml.jackson.core.io.TestUTF32Reader.testInvalidInput(TestUTF32Reader.java:32)
```

### LINKED ISSUE #418: ArrayIndexOutOfBoundsException from UTF32Reader.read on invalid input
I was doing some fuzz testing and came across an `ArrayIndexOutOfBoundsException`. It seems like it is related to FasterXML/jackson-core/issues/382 in that it has introduced a bug which if the byte[] is a %3 it will still produce an `ArrayIndexOutOfBoundsException`.

Simple test case as follows: 

```Java
public void testInvalidInput() throws IOException {
        byte[] data = new byte[7];
        JsonParser parser = FACTORY.createParser(ObjectReadContext.empty(), data);
        parser.nextToken();
        parser.close();
    }
```
Stack trace:
```
java.lang.ArrayIndexOutOfBoundsException: 7

	at com.fasterxml.jackson.core.io.UTF32Reader.read(UTF32Reader.java:145)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:229)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2316)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:632)
	at com.fasterxml.jackson.core.read.UTF32ParseTest.testInvalidInput(UTF32ParseTest.java:61)
```

Just for clarity the following test case produces the correct `JsonParseExecption`
```Java
public void testInvalidInput() throws IOException {
        byte[] data = new byte[8];
        JsonParser parser = FACTORY.createParser(ObjectReadContext.empty(), data);
        parser.nextToken();
        parser.close();
    }
```
Stack trace:
```
com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (byte[])"        "; line: 1, column: 2]

	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1666)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:674)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:625)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2335)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:632)
	at com.fasterxml.jackson.core.read.UTF32ParseTest.testInvalidInput(UTF32ParseTest.java:61)
```

### PR DESCRIPTION
**Pull request by pfitzsimons-r7**
Fix #382, Add test case to check fix.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
looks good, thank you!

One clerical thing: unless we have asked for and received for one, we need CLA from:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

(or Corporate CLA that's next to it).

Usually it's easiest to print, fill & sign, scan, email to `info` at fasterxml dot com.
This is only needed before the first contribution, after which we can merge any number of contributions.

Looking forward to merging the fix; thank you once again!

**Comment by pfitzsimons-r7** [comment]
Hi @cowtowncoder I've sent off that CLA now.

Out of curiosity - do you have an idea of when this will be released ?

**Comment by cowtowncoder** [comment]
@pfitzsimons-r7 Thanks!

As to release, it will probably take a while just because 2.9.2 was released 6 days ago, and at this point releases tend to be at least one month apart (but more likely 2).
And whether there will be new releases for 2.8 (that'd be 2.8.11) is also uncertain.

**Comment by pfitzsimons-r7** [comment]
That's great @cowtowncoder thanks for the information! Look forward to future contributions.

**Comment by cowtowncoder** [comment]
Thank you again for reporting, patching. Looking forward to more contributions! :)

**Comment by pfitzsimons-r7** [comment]
@cowtowncoder is there a planned release date for this change?

**Comment by cowtowncoder** [comment]
It will be in:

* https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.11
* https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.3

and although we do not set strict dates in advance I think early December is a likely target date for `2.9.3` (and definitely before end of December)
And if I am doing a release then I will probably go ahead and also do `2.8.11` to flush out what may be the last regular fixes for 2.8 branch.

**Pull request merged**
