### PR TITLE
Allow override of `StreamReadContraints` default with `overrideDefaultStreamReadConstraints()`

### PR DESCRIPTION
**Pull request by pjfanning**
if this approach is acceptable, I can extend this PR with some tests

### CODE REVIEW

**Comment by cowtowncoder** [comment]
As per my other note, I don't want to make API changes in 2.15. Will release 2.15.1 soon; this PR may be left as fallback in case there really is enough push back to require addition (i.e. I can still consider change, 2.15.2 or 2.15.1 makes little difference semantically).

**Comment by darrenoc3** [comment]
@cowtowncoder I am just one person, but consider this my pushback: it's extremely inconvenient for legacy projects that are already handling documents >5MB or greater in production to have no mechanism to configure the default globally. You can see another example in Github where Palantir have had to jump through hoops and use Reflection to override the default in their codebase.

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
I am coming around to thinking this would make sense for 2.15.2. I'll think about it bit more but will probably merge it.

**Comment by cowtowncoder** [comment]
@pjfanning Is this ready to be merged? Only asking as it's still in Draft stage.

**Comment by pjfanning** [comment]
@cowtowncoder this is ready to merge

**Review by cowtowncoder — APPROVED** [review]

**Pull request merged**
