### PR TITLE
add propertyNamesSpliterator

### PR DESCRIPTION
**Pull request by pjfanning**
will likely break downstream Jackson projects until we implement the equivalent method

### CODE REVIEW

**Comment by JooHyukKim** [comment]
Is this part of any JSTEP? If not I think we can add somewhere in JSTEP for migration doc later on.

**Comment by cowtowncoder** [comment]
> Is this part of any JSTEP? If not I think we can add somewhere in JSTEP for 2->3 migration doc later on.

Would belong under https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP-3 and I think @pjfanning probably noticed my adding #4863 (sort of related). `TreeNode` additions are bit limited due to Java limitation on co-variance (cannot add return value of `Stream<TreeNode>` because not legal to override with `Stream<JsonNode>`) but can do this for property names (since keys are still `String`s).

**Comment by cowtowncoder** [comment]
@pjfanning Quick question on need/rationale here: I forget details of how `Spliterator`s are useful (as building blocks for Streams... ? ). So would this be useful for actual use cases?

**Comment by pjfanning** [comment]
I saw the changes for stream support and spliterators are most used as an iterator that can be split and processed in parallel (eg parallel streams).
The changes don't look very drastic so I'm happy to not merge the changes and wait to see if there is explicit demand for this.

**Comment by cowtowncoder** [comment]
> I saw the changes for stream support and spliterators are most used as an iterator that can be split and processed in parallel (eg parallel streams). The changes don't look very drastic so I'm happy to not merge the changes and wait to see if there is explicit demand for this. What I mean is that changes like this could be added at any time if needed and they don't really need a major release.

Correct, except for one thing: to add method in `TreeNode` there either needs to be default method implementation, or needs to go in a major version.

I'll have a look at `jackson-databind` side and see if that makes.

Also, fwtw, I try to keep [JSTEP-3](https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP-3) updated with changes to `JsonNode` / `TreeNode`, although it's obviously challenging to keep related-but-not-synced things in-sync manually (github not having something for "uber-issues" like... epics or something).

**Comment by pjfanning** [comment]
I've added a propertyNamesSpliterator default impl.

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
Realized somewhat late that name needs to be `propertyNameSpliterator()` since we will use:

1. Plulars for actual `Collection`/`Set` (JsonNode.values())`
2. But Singulars for streams (`valueStream()`) and thereby spliterators as well.

Will change accordingly.

**Comment by JooHyukKim** [comment]
> Realized somewhat late that name needs to be `propertyNameSpliterator()` since we will use:

Is there a written form of this convention somewhere? We could probably go make one in the main '/Jackson' repo

**Comment by cowtowncoder** [comment]
Right: there's JSTEP-6 (https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP-6) for this. But I need to update that wrt this part of naming.

**Pull request merged**
