### PR TITLE
Reproduction for #1161: FastDoubleParser NPE

### PR DESCRIPTION
**Pull request by cowtowncoder**
Note: looks like the issue specifically affects parsing from `char[]`, but not (for some reason), `String`.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@pjfanning Looks like FDP has some odd issue with variant of `BigDecimal` parsing method(s) that take `char[]`. I can work around the issue by using `String` taking methods but it'd be better to figure out root cause.

**Comment by pjfanning** [comment]
this will need to reported upstream to the fastdoubleparser team

**Comment by pjfanning** [comment]
created https://github.com/wrandelshofer/FastDoubleParser/pull/77

**Comment by cowtowncoder** [comment]
Thank you @pjfanning.

**Pull request merged**
