### PR TITLE
fastdoubleparser 1.0.0 (#1163)

### PR DESCRIPTION
**Pull request by pjfanning**
backport #1163

### CODE REVIEW

**Comment by pjfanning** [comment]
@cowtowncoder this would almost certainly backport cleanly to 2.15 if there were any plans for a future 2.15 release

2.15 uses fastdoubleparser 0.9.0 already so same change should work there too

**Comment by JooHyukKim** [comment]
> this would almost certainly backport cleanly to 2.15

If so, we need to create a new PR based on 2.15 branch. That way we can just forward merge.

**Comment by cowtowncoder** [comment]
@JooHyukKim Normally yes, but unfortunately `pom.xml` changes are different due to merge conflict wrt release version. As a result, manual merge (or separate PRs) are typically needed.

@pjfanning Yes, I think 2.15 backport would be welcome too if and when it's easy to do. There will likely be one more patch release from that branch (2.15.4).

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
@pjfanning whops. Did not notice but this was (accidentally I assume) against `2.17`, not 2.16?

**Comment by pjfanning** [comment]
This PR was targeting the wrong barnch. I have created #1165 for 2.16 branch.

**Pull request merged**
