### PR TITLE
Make `BigInteger` parsing lazy

### PR DESCRIPTION
**Pull request by pjfanning**
@cowtowncoder please feel free to reject this - but this relatively small change might be useful for v2.14

This is useful for https://github.com/rallyhealth/weePickle/issues/118

This change means that JsonParser.getNumberType will not need to parse the BigInteger but if you later need the BigInteger (getBigIntegerValue() call), it will then be parsed (just once).

It may also be useful to do something similar with BigDecimal parsing but that change is not as immediately useful.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@pjfanning Excellent! I am thinking I do need to release `2.14.0-rc3`, but these are important improvements I think so that's fine. And yes, testing might show that similar would make sense for `BigDecimal`, but one step at a time.
I hope this merges cleanly to `master` but we'll see.

I hope testing we have is able to find edge cases there might be but... we'll see.

**Comment by cowtowncoder** [comment]
@pjfanning One thing we could do eagerly would to add accessor (I renamed one here to `_getBigInteger()`, minor naming convention thing) for `BigDecimal` too; even if at first it'd still be eagerly accessed.
So something like

```
    protected BigDecimal _getBigDecimal() { return _numberBigDecimal; }
```

in hindsight these probably should have been there from beginning.

**Comment by pjfanning** [comment]
@cowtowncoder I've made big decimal lazy too and renamed the private methods

**Comment by cowtowncoder** [comment]
@pjfanning Is there a PR? I merged this one earlier.

**Comment by pjfanning** [comment]
@cowtowncoder I created https://github.com/FasterXML/jackson-core/pull/830 - I hadn't noticed that this PR was merged and thought that my changes in the related branch would update this PR

**Comment by cowtowncoder** [comment]
Ah. Thank you for creating a new PR, I think updates after merge may not be visible.

**Pull request merged**
