### PR TITLE
latest license updates

### PR DESCRIPTION
**Pull request by pjfanning**
based on https://github.com/FasterXML/jackson-core/issues/1002#issuecomment-1528808737

this is only for jackson 2.14 to unblock a potential v2.14.3 release - we have more time to worry about getting v2.15 licenses sorted out

### CODE REVIEW

**Comment by pjfanning** [comment]
@cowtowncoder I got distracted while doing this PR and accidentally merged this when I thought I was only submitting it

Feel free to revert it and we can do a new one to replace it

**Comment by cowtowncoder** [comment]
@pjfanning No that's perfectly fine, not a problem. I'll try merging it forward.

Thank you for doing it so quickly.

**Comment by cowtowncoder** [comment]
Sigh. I know it's unavoidable, but I wish we didn't have to replicate almost identical 10kB licenses like this.
I know it gets compressed and it really doesn't matter but somehow makes me sad :)

But I really hope this avoids getting more requests, comments, by interested third parties. What bugs me is really the fact that none of actually relevant parties -- authors of packages themselves, and us -- had concerns, but it's others who are worried about hypothetical issues if relevant parties somehow did no longer (?) agree or something.
It's always very easy to file issues for others to take care of.
</rant>

**Comment by cowtowncoder** [comment]
@pjfanning There were minor merge conflicts 2.14->2.15; I hope I resolved those correctly.

**Comment by pjfanning** [comment]
@cowtowncoder this PR was not meant to be forward to 2.15 branch - see my description in the PR.

For Jackson 2.15, my plan really is to uptake the latest FastDoubleParser 0.9.0 release made today.

I had meant to do a PR for 2.15 branch but messed it up again and accidentally committed to 2.15 branch directly. I am travelling this weekend and am busy with stuff related to that and am struggling to concentrate on these commits.

https://github.com/FasterXML/jackson-core/commit/7c11ed0014f5811a9038e8b6b1f9565453a4058f is my accidental commit. This reverts part of the forward fit.

I am deliberately using the MIT license of FastDoubleParser for Jackson 2.15+. It is much easier to use the default license instead of having a special Jackson only license for FastDoubleParser and all the confusion from that. Especially, since we now shade the FastDoubleParser source (new in Jackson 21.5 - Jackson 2.14 is different, the FastDoubleParser is checked into jackson-core repo and the source has adjusted Apache headers.

**Comment by cowtowncoder** [comment]
@pjfanning Ok, sorry about messing things up some more. I'll revert my merge then.

**Pull request merged**
