### PR TITLE
Fix #1277: add JDK 22 optimizations back to FDP

### LINKED ISSUE #1277: Add back Java 22 optimisation in fastdoubleparser
The pom.xml removes the Java 22 classes for fastdoubleparser. Maven Shade plugin settings. Will also need to add a relocation setting.

It should be safe to add them back now. Build tools have releases that support Java 22 format classes.

### PR DESCRIPTION
**Pull request by cowtowncoder**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@pjfanning Is this what is needed or #1277 ?

**Comment by cowtowncoder** [comment]
Ok, there seems to be an issue; maybe due to Shade plugin not working with JDK 22 bytecode.
There's a newer version; need to update version via `oss-parent` tomorrow.

**Comment by cowtowncoder** [comment]
Ok so either Shade plugin, or latest Maven, fixed the problem: CI passes now.

**Review by pjfanning — APPROVED** [review]
Lgtm

**Pull request merged**
